events/urls.py
from django.urls import path


from . import views

urlpatterns = [
    path('', views.index, name="home"),
    path('volunteering/', views.volunteering, name="volunteering"),
    path('event/<str:pk>/', views.event,name='event'),
    path('stories/', views.stories, name="stories"),
    path('story/<str:pk>/', views.story, name="story"),
    path('register/', views.register, name="register"),
    path('login/', views.loginPage, name='login'),
    path('attend/<str:pk>/', views.attend, name="attend"),
    path('logout/', views.logoutUser, name="logout"),
]

harding/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('events.urls')),

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Volunteer(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    user_name = models.CharField(max_length=200, null=True, blank=True)
    first_name = models.CharField(max_length=200, null=True, blank=True)
    last_name = models.CharField(max_length=200, null=True, blank=True)
    user_rank = models.IntegerField(default=0)
    user_points = models.IntegerField(default = 0)
    user_coins = models.IntegerField(default = 0)
    user_icon = models.ImageField(default='profile1.png', null=True, blank=True)
    user_datecreated = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        if self.user_name is not None:

            return self.user_name
        else:
            return "default"

class Tag(models.Model):
    name = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name

class Post(models.Model):
    TYPE = ('Event', 'Event'), ('Story', 'Story')

    content_name = models.CharField(max_length=200, null=True)
    content_author = models.ForeignKey(Volunteer, null=True, on_delete=models.SET_NULL)
    content_date = models.DateTimeField(auto_now_add=True)
    content_date_start = models.DateTimeField(null=True, blank=True)
    content_date_end = models.DateTimeField(null=True, blank=True)
    content_social_description = models.CharField(max_length=1000, null=True)
    content_image = models.ImageField(default='profile1.png', null=True, blank=True)
    tags = models.ManyToManyField(Tag)
    full_story = models.CharField(max_length=10000, null=True, blank=True)
    post_type = models.CharField(max_length=200, null=True, choices=TYPE)
    attending = models.ManyToManyField(User)
    


    def __str__(self):
        return self.content_name



class Comment(models.Model):
    message = models.CharField(max_length=300, null=True)
    author = models.ForeignKey(Volunteer, null=True, on_delete=models.CASCADE)
    post = models.ManyToManyField(Post)

events/forms.py
from .models import Comment
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class CommentForm(ModelForm):
    message = forms.CharField(widget=forms.Textarea(attrs={"rows":3}))
    class Meta:
        model = Comment
        fields = ['message']


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

events/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from .filters import PostFilter
from django.contrib.auth.forms import UserCreationForm
from .forms import CommentForm, CreateUserForm
from .models import *
from .decorators import *
from django.contrib.auth.decorators import login_required
from django.contrib import messages
import requests
import json

# Create your views here.
@login_required(login_url='login')
def index(request):
    response = requests.get('http://hardingdevelopment.nexisit.net/harding_api/api_event_search.php?page_num=0&per_page=20&buckets=Volunteering&timezone=25200&app_server_version=3.2&app_version=2&app_build=1&user_id=2&token=70aedda35dca9c192ef551c9f7b570e0&salt=309a9bea4d2695656e83f4fe7b340ee0&app=1&version=3.2').json()

    return render(request, 'events/home.html', {'response':response})


def volunteering(request):
    posts = Post.objects.filter(post_type='Event')
    myFilter = PostFilter(request.GET, queryset=posts)
    posts = myFilter.qs
    context={'posts':posts, 'myFilter':myFilter}
    return render(request, 'events/volunteering.html', context)

def event(request, pk):
    post = Post.objects.get(id=pk)
    form = CommentForm()
    context = {'post':post, 'form':form}
    
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save()
            comment.author = request.user.volunteer
            post.comment_set.add(comment)
            comment.save()
            return redirect('event', pk)
    return render(request,'events/event.html', context )

def attend(request, pk):
    user = request.user
    post = Post.objects.get(id=pk)
    post.attending.add(user)
    post.save()
    return redirect('/')
    

def stories(request):
    posts = Post.objects.filter(post_type='Story')
    myFilter = PostFilter(request.GET, queryset=posts)
    posts = myFilter.qs
    context={'posts':posts, 'myFilter':myFilter}
    return render(request, 'events/stories.html', context)

def story(request, pk):
    post = Post.objects.get(id=pk)
    form = CommentForm()
    context = {'post':post, 'form':form}
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save()
            comment.author = request.user.volunteer
            post.comment_set.add(comment)
            comment.save()
            return redirect('story', pk)
    return render(request,'events/story.html', context)

def register(request):
    #this functionality stops a user from visiting register while logged int
    form = CreateUserForm()
    context={'form':form}
    template = 'events/register.html'
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            volunteer = Volunteer(user=user, user_name=user.username)
            volunteer.save()
            messages.success(request, 'Account was created for ' + username)
            return redirect('/')
        else:
            messages.error(request, 'Something went wrong, please try again.')
    return render(request, template, context)


def loginPage(request):
    form=UserCreationForm()
    context={'form':form}
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            messages.error(request, 'Username or password is incorrect')
    template = 'events/login.html'
    return render(request, template, context)

def logoutUser(request):
    logout(request)
    return redirect('login')

events/templates/events/event.html
{% extends "events/main.html" %}

{% block content %}
<div class="row">
    <div class="card mb-3">
        <img class="card-img-top" src="{{post.content_image.url}}" alt="Card image cap">
        <div class="card-body">
          <h2 class="card-title">{{post.content_name}}</h2>
          {% for tag in post.tags.all %}
            <strong>{{tag}}</strong>
          {% endfor %}
        
          <p>{{post.content_social_description}}</p>
          <p class="card-text"><small class="text-muted">{{post.content_date_start}} - {{post.content_date_end}}</small></p>
          <div class="buttons">
          <a class="btn btn-info" href="#comment-form">Comment</a>
          <a class="btn btn-info" href="{% url 'attend' post.id %}">Attend</a>
          <a class="btn btn-info" href="{% url 'event' post.id %}">Favorite</a>
          <a class="btn btn-info" href="{% url 'event' post.id %}">Share</a>
          </div>
        </div>
      </div>
</div>
<h4 style="margin-left: 5px;">Comments</h4>
{% for comment in post.comment_set.all %}
<div class="row comments">
    <strong>{{comment.author.user_name}}: </strong>
    {{comment.message}}
    
</div>
{% endfor %}

<div class="row comments" id="comment-form">
    <form method="POST">
    
        {% csrf_token %}
        {{form}}
        <input type="submit" name="Post">
    </form>
</div>



{% endblock %}

events/templates/events/home.html
{% extends "events/main.html" %}
{% load static %}
{% include "events/navbar.html" %}
{% block content %}

<h2>Home</h2>
<div class="comments">
<div class="card" style="width: 18rem;">
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Rank: {{request.user.volunteer.user_rank}}</li>
    <li class="list-group-item">Points: {{request.user.volunteer.user_points}}</li>
    <li class="list-group-item">Coins: {{request.user.volunteer.user_coins}}</li>
  </ul>
</div>
<hr>


</div>
<div style="margin-left:5px;"class="row mt-3">
  <h3>Your Events</h3>
  {% for post in request.user.post_set.all %}
  <div class="row">
    <div class="card mb-3">
        <img class="card-img-top" src="{{post.content_image.url}}" alt="Card image cap">
        <div class="card-body">
          <h2 class="card-title">{{post.content_name}}</h2>
          {% for tag in post.tags.all %}
            <strong>{{tag}}</strong>
          {% endfor %}
        
          <p>{{post.content_social_description}}</p>
          <p class="card-text"><small class="text-muted">{{post.content_date_start}} - {{post.content_date_end}}</small></p>
          <a class="btn btn-primary" href="{% url 'event' post.id %}">Learn More</a>
        </div>
      </div>
</div>
  {% endfor %}
</div>


<div style="margin-left:5px;"class="row mt-3">
  <h3>Favorited Events</h3>
</div>





  


{% endblock %}

events/templates/events/login.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">

					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                         {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>
                {% for message in messages %}
                <p id="messages">{{message}}</p>

                {% endfor %}
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'register' %}" class="ml-2">Sign Up</a>
					</div>
					
					
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

events/templates/events/main.html
<!DOCTYPE html>
{% load static %}

<html>
    <head>
        <meta charset="utf-8">
    
        <title>Harding Development</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static '/css/main.css' %}">

    </head>
    <body>
        <!-- This tag brings in the navbar to the main template -->
        {% include 'events/navbar.html' %}
        
        <!-- Every page's content will go into this block content -->
        {% block content %}


        {% endblock %}
        <hr>

        <h5>Our footer</h5>
        
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    </body>
</html>

events/templates/events/navbar.html
{% load static %} 

<nav style="width: 100%;"class="navbar sticky-top navbar-light bg-light">
    <div class="row">
    <a class="navbar-brand" href="{% url 'home' %}"><h1>Harding Development</h1></a>
    </div>
    <div class="row">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-item nav-link" href="{% url 'home' %}">Home</a>
        </li>
        
        <li class="nav-item">
          <a class="nav-item nav-link" href="{% url 'stories' %}">Stories</a>
        </li>
        
        
  
        
        <li class="nav-item">
          <a class="nav-item nav-link" href="{% url 'volunteering' %}">Volunteering</a>
        </li>

        <li class="nav-item">
          <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
        </div>
        
        
        
        
      </ul>
      
    </div>
    
  </nav>

events/templates/events/register.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Register</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
                     
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
                            </div>
							{{form.username}}
                        </div>
                        
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{form.email}}
                        </div>
                        
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password2}}
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>
					</form>
				</div>
                {% for message in messages %}
                <p>{{message}}</p>

                {% endfor %}
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'login' %}" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Enter password...';
		form_fields[4].placeholder='Re-enter Password...';


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>

events/templates/events/stories.html
{% extends "events/main.html" %}

{% block content %}
<h2>Stories</h2>
<div class="row">
    <div class="col">
        <div class="card card-body">
            <form method="get">
                {{myFilter.form}}
                <button class="btn btn-primary" type="submit">Search</button>
            </form>
        </div>
    </div>
</div>

{% for post in posts %}
  

<div class="row">
    <div class="card mb-3">
        <img class="card-img-top" src="{{post.content_image.url}}" alt="Card image cap">
        <div class="card-body">
          <h2 class="card-title">{{post.content_name}}</h2>
          {% for tag in post.tags.all %}
            <strong>{{tag}}</strong>
          {% endfor %}
        
          <p>{{post.content_social_description}}</p>
          <p class="card-text"><small class="text-muted">{{post.content_date_start}} - {{post.content_date_end}}</small></p>
          <a class="btn btn-primary" href="{% url 'story' post.id %}">Read More</a>
        </div>
      </div>
</div>
{% endfor %}


{% endblock %}

events/templates/events/story.html
{% extends "events/main.html" %}

{% block content %}
<div class="row">
    <div class="card mb-3">
        <img class="card-img-top" src="{{post.content_image.url}}" alt="Card image cap">
        <div class="card-body">
          <h2 class="card-title">{{post.content_name}}</h2>
          {% for tag in post.tags.all %}
            <strong>{{tag}}</strong>
          {% endfor %}
        
          <p>{{post.full_story}}</p>
          <p class="card-text"><small class="text-muted">{{post.content_date_start}} - {{post.content_date_end}}</small></p>
          <div class="buttons">
          <a class="btn btn-info" href="#comment-form">Comment</a>
          
          <a class="btn btn-info" href="{% url 'event' post.id %}">Favorite</a>
          <a class="btn btn-info" href="{% url 'event' post.id %}">Share</a>
          </div>
        </div>
      </div>
</div>
<h4 style="margin-left: 5px;">Comments</h4>
{% for comment in post.comment_set.all %}
<div class="row comments">
    <strong>{{comment.author.user_name}}:</strong>
    {{comment.message}}
    
</div>
{% endfor %}

<div class="row comments" id="comment-form">
    <form method="POST">
    
        {% csrf_token %}
        {{form}}
        <input type="submit" name="Post">
    </form>
</div>



{% endblock %}

events/templates/events/volunteering.html
{% extends "events/main.html" %}

{% block content %}
<h2>Volunteering</h2>
<div class="row">
    <div class="col">
        <div class="card card-body">
            <form method="get">
                {{myFilter.form}}
                <button class="btn btn-primary" type="submit">Search</button>
            </form>
        </div>
    </div>
</div>

{% for post in posts %}
  

<div class="row">
    <div class="card mb-3">
        <img class="card-img-top" src="{{post.content_image.url}}" alt="Card image cap">
        <div class="card-body">
          <h2 class="card-title">{{post.content_name}}</h2>
          {% for tag in post.tags.all %}
            <strong>{{tag}}</strong>
          {% endfor %}
        
          <p>{{post.content_social_description}}</p>
          <p class="card-text"><small class="text-muted">{{post.content_date_start}} - {{post.content_date_end}}</small></p>
          <a class="btn btn-primary" href="{% url 'event' post.id %}">Learn More</a>
        </div>
      </div>
</div>
{% endfor %}


{% endblock %}